#Usamos la imagen oficial de Node.JS
FROM node:20-slim

#Creamos y usamos la carpeta de trabajo
WORKDIR /frontend

#Copiamos el package json y package-lock.json para instalar las dependencias
COPY package.json package-lock.json* ./

#Instalamos las dependecias de React
RUN npm install

#Copiamos todo el codigo fuente de React
COPY . .

ENV NEXT_PUBLIC_AUTH_API_URL=http://localhost:5000/auth
ENV NEXT_PUBLIC_USER_API_URL=http://localhost:5000/user

#Ejecutamos el build de react para generar los archivos estaticos
RUN npm run build

#Exponemos el puerto en el que react correrá
EXPOSE 3000

# Instalar curl para debug (opcional)
# RUN apt-get update && apt-get install -y curl


#Construmos la sentencia CMD
CMD ["npm","start"]